// Copyright IBM Corp. 2015, 2026
// SPDX-License-Identifier: MPL-2.0
//
// Modifications Copyright (c) 2026 Ville Vesilehto
// Derived from github.com/hashicorp/go-memdb watch_few.go @ 7d3fdd5.

// Code generated by watch-gen/main.go; DO NOT EDIT.

package memdb

//go:generate sh -c "go run watch-gen/main.go >watch_few.go"

import (
	"time"
)

// aFew is upstream's name for the number of channels one select handles. It
// is kept because upstream's tests refer to it; see maxFew for the real limit.
const aFew = 32

// maxFew is the largest number of channels a single select waits on.
const maxFew = 128

// fanoutChunk is how many channels each helper goroutine of a bigger watch set
// waits on.
const fanoutChunk = 32

// watchChunk is what a helper goroutine runs: the select over exactly
// fanoutChunk channels, called directly. Going through watchFewDone would put
// its frame between the goroutine and the select, and on a new goroutine's
// small stack that is enough to move the first stack growth from somewhere
// inside the runtime to the entry of the big select function -- where growing
// is expensive, because the runtime walks that function's long stack table to
// size the new stack. Measured on x86-64, it made a watch on 1024 channels 6%
// slower than upstream's.
func watchChunk(done <-chan struct{}, ch []<-chan struct{}) int {
	return watchFewDone32(done, ch)
}

// What ended a wait.
const (
	watchFired   = iota // one of the watch channels
	watchDone           // the done channel (a cancelled context)
	watchTimeout        // the timeout channel
)

// A wait ends on a watch channel or on the one "other" channel of the call:
// the done channel of a context (WatchCtx, and the helper goroutines of a big
// set) or a timeout channel (Watch). Each gets its own ladder of selects, so
// that no select carries an arm its caller never uses.

// watchFewDone waits on the first n channels of ch and on done, in a single
// select of the smallest sufficient size. Unused channels and done may be nil:
// a nil channel is never ready.
func watchFewDone(n int, done <-chan struct{}, ch []<-chan struct{}) int {
	switch {
	case n <= 1:
		return watchFewDone1(done, ch)
	case n <= 2:
		return watchFewDone2(done, ch)
	case n <= 4:
		return watchFewDone4(done, ch)
	case n <= 8:
		return watchFewDone8(done, ch)
	case n <= 16:
		return watchFewDone16(done, ch)
	case n <= 32:
		return watchFewDone32(done, ch)
	case n <= 64:
		return watchFewDone64(done, ch)
	case n <= 128:
		return watchFewDone128(done, ch)
	}
	panic("memdb: watchFewDone called with too many channels")
}

// watchFewTimeout is watchFewDone for a timeout channel.
func watchFewTimeout(n int, timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	switch {
	case n <= 1:
		return watchFewTimeout1(timeoutCh, ch)
	case n <= 2:
		return watchFewTimeout2(timeoutCh, ch)
	case n <= 4:
		return watchFewTimeout4(timeoutCh, ch)
	case n <= 8:
		return watchFewTimeout8(timeoutCh, ch)
	case n <= 16:
		return watchFewTimeout16(timeoutCh, ch)
	case n <= 32:
		return watchFewTimeout32(timeoutCh, ch)
	case n <= 64:
		return watchFewTimeout64(timeoutCh, ch)
	case n <= 128:
		return watchFewTimeout128(timeoutCh, ch)
	}
	panic("memdb: watchFewTimeout called with too many channels")
}

func watchFewDone1(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[0]
	select {
	case <-ch[0]:
		return watchFired
	case <-done:
		return watchDone
	}
}

func watchFewTimeout1(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[0]
	select {
	case <-ch[0]:
		return watchFired
	case <-timeoutCh:
		return watchTimeout
	}
}

func watchFewDone2(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[1]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-done:
		return watchDone
	}
}

func watchFewTimeout2(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[1]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-timeoutCh:
		return watchTimeout
	}
}

func watchFewDone4(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[3]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-done:
		return watchDone
	}
}

func watchFewTimeout4(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[3]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-timeoutCh:
		return watchTimeout
	}
}

func watchFewDone8(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[7]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-done:
		return watchDone
	}
}

func watchFewTimeout8(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[7]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-timeoutCh:
		return watchTimeout
	}
}

func watchFewDone16(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[15]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-ch[8]:
		return watchFired
	case <-ch[9]:
		return watchFired
	case <-ch[10]:
		return watchFired
	case <-ch[11]:
		return watchFired
	case <-ch[12]:
		return watchFired
	case <-ch[13]:
		return watchFired
	case <-ch[14]:
		return watchFired
	case <-ch[15]:
		return watchFired
	case <-done:
		return watchDone
	}
}

func watchFewTimeout16(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[15]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-ch[8]:
		return watchFired
	case <-ch[9]:
		return watchFired
	case <-ch[10]:
		return watchFired
	case <-ch[11]:
		return watchFired
	case <-ch[12]:
		return watchFired
	case <-ch[13]:
		return watchFired
	case <-ch[14]:
		return watchFired
	case <-ch[15]:
		return watchFired
	case <-timeoutCh:
		return watchTimeout
	}
}

func watchFewDone32(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[31]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-ch[8]:
		return watchFired
	case <-ch[9]:
		return watchFired
	case <-ch[10]:
		return watchFired
	case <-ch[11]:
		return watchFired
	case <-ch[12]:
		return watchFired
	case <-ch[13]:
		return watchFired
	case <-ch[14]:
		return watchFired
	case <-ch[15]:
		return watchFired
	case <-ch[16]:
		return watchFired
	case <-ch[17]:
		return watchFired
	case <-ch[18]:
		return watchFired
	case <-ch[19]:
		return watchFired
	case <-ch[20]:
		return watchFired
	case <-ch[21]:
		return watchFired
	case <-ch[22]:
		return watchFired
	case <-ch[23]:
		return watchFired
	case <-ch[24]:
		return watchFired
	case <-ch[25]:
		return watchFired
	case <-ch[26]:
		return watchFired
	case <-ch[27]:
		return watchFired
	case <-ch[28]:
		return watchFired
	case <-ch[29]:
		return watchFired
	case <-ch[30]:
		return watchFired
	case <-ch[31]:
		return watchFired
	case <-done:
		return watchDone
	}
}

func watchFewTimeout32(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[31]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-ch[8]:
		return watchFired
	case <-ch[9]:
		return watchFired
	case <-ch[10]:
		return watchFired
	case <-ch[11]:
		return watchFired
	case <-ch[12]:
		return watchFired
	case <-ch[13]:
		return watchFired
	case <-ch[14]:
		return watchFired
	case <-ch[15]:
		return watchFired
	case <-ch[16]:
		return watchFired
	case <-ch[17]:
		return watchFired
	case <-ch[18]:
		return watchFired
	case <-ch[19]:
		return watchFired
	case <-ch[20]:
		return watchFired
	case <-ch[21]:
		return watchFired
	case <-ch[22]:
		return watchFired
	case <-ch[23]:
		return watchFired
	case <-ch[24]:
		return watchFired
	case <-ch[25]:
		return watchFired
	case <-ch[26]:
		return watchFired
	case <-ch[27]:
		return watchFired
	case <-ch[28]:
		return watchFired
	case <-ch[29]:
		return watchFired
	case <-ch[30]:
		return watchFired
	case <-ch[31]:
		return watchFired
	case <-timeoutCh:
		return watchTimeout
	}
}

func watchFewDone64(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[63]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-ch[8]:
		return watchFired
	case <-ch[9]:
		return watchFired
	case <-ch[10]:
		return watchFired
	case <-ch[11]:
		return watchFired
	case <-ch[12]:
		return watchFired
	case <-ch[13]:
		return watchFired
	case <-ch[14]:
		return watchFired
	case <-ch[15]:
		return watchFired
	case <-ch[16]:
		return watchFired
	case <-ch[17]:
		return watchFired
	case <-ch[18]:
		return watchFired
	case <-ch[19]:
		return watchFired
	case <-ch[20]:
		return watchFired
	case <-ch[21]:
		return watchFired
	case <-ch[22]:
		return watchFired
	case <-ch[23]:
		return watchFired
	case <-ch[24]:
		return watchFired
	case <-ch[25]:
		return watchFired
	case <-ch[26]:
		return watchFired
	case <-ch[27]:
		return watchFired
	case <-ch[28]:
		return watchFired
	case <-ch[29]:
		return watchFired
	case <-ch[30]:
		return watchFired
	case <-ch[31]:
		return watchFired
	case <-ch[32]:
		return watchFired
	case <-ch[33]:
		return watchFired
	case <-ch[34]:
		return watchFired
	case <-ch[35]:
		return watchFired
	case <-ch[36]:
		return watchFired
	case <-ch[37]:
		return watchFired
	case <-ch[38]:
		return watchFired
	case <-ch[39]:
		return watchFired
	case <-ch[40]:
		return watchFired
	case <-ch[41]:
		return watchFired
	case <-ch[42]:
		return watchFired
	case <-ch[43]:
		return watchFired
	case <-ch[44]:
		return watchFired
	case <-ch[45]:
		return watchFired
	case <-ch[46]:
		return watchFired
	case <-ch[47]:
		return watchFired
	case <-ch[48]:
		return watchFired
	case <-ch[49]:
		return watchFired
	case <-ch[50]:
		return watchFired
	case <-ch[51]:
		return watchFired
	case <-ch[52]:
		return watchFired
	case <-ch[53]:
		return watchFired
	case <-ch[54]:
		return watchFired
	case <-ch[55]:
		return watchFired
	case <-ch[56]:
		return watchFired
	case <-ch[57]:
		return watchFired
	case <-ch[58]:
		return watchFired
	case <-ch[59]:
		return watchFired
	case <-ch[60]:
		return watchFired
	case <-ch[61]:
		return watchFired
	case <-ch[62]:
		return watchFired
	case <-ch[63]:
		return watchFired
	case <-done:
		return watchDone
	}
}

func watchFewTimeout64(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[63]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-ch[8]:
		return watchFired
	case <-ch[9]:
		return watchFired
	case <-ch[10]:
		return watchFired
	case <-ch[11]:
		return watchFired
	case <-ch[12]:
		return watchFired
	case <-ch[13]:
		return watchFired
	case <-ch[14]:
		return watchFired
	case <-ch[15]:
		return watchFired
	case <-ch[16]:
		return watchFired
	case <-ch[17]:
		return watchFired
	case <-ch[18]:
		return watchFired
	case <-ch[19]:
		return watchFired
	case <-ch[20]:
		return watchFired
	case <-ch[21]:
		return watchFired
	case <-ch[22]:
		return watchFired
	case <-ch[23]:
		return watchFired
	case <-ch[24]:
		return watchFired
	case <-ch[25]:
		return watchFired
	case <-ch[26]:
		return watchFired
	case <-ch[27]:
		return watchFired
	case <-ch[28]:
		return watchFired
	case <-ch[29]:
		return watchFired
	case <-ch[30]:
		return watchFired
	case <-ch[31]:
		return watchFired
	case <-ch[32]:
		return watchFired
	case <-ch[33]:
		return watchFired
	case <-ch[34]:
		return watchFired
	case <-ch[35]:
		return watchFired
	case <-ch[36]:
		return watchFired
	case <-ch[37]:
		return watchFired
	case <-ch[38]:
		return watchFired
	case <-ch[39]:
		return watchFired
	case <-ch[40]:
		return watchFired
	case <-ch[41]:
		return watchFired
	case <-ch[42]:
		return watchFired
	case <-ch[43]:
		return watchFired
	case <-ch[44]:
		return watchFired
	case <-ch[45]:
		return watchFired
	case <-ch[46]:
		return watchFired
	case <-ch[47]:
		return watchFired
	case <-ch[48]:
		return watchFired
	case <-ch[49]:
		return watchFired
	case <-ch[50]:
		return watchFired
	case <-ch[51]:
		return watchFired
	case <-ch[52]:
		return watchFired
	case <-ch[53]:
		return watchFired
	case <-ch[54]:
		return watchFired
	case <-ch[55]:
		return watchFired
	case <-ch[56]:
		return watchFired
	case <-ch[57]:
		return watchFired
	case <-ch[58]:
		return watchFired
	case <-ch[59]:
		return watchFired
	case <-ch[60]:
		return watchFired
	case <-ch[61]:
		return watchFired
	case <-ch[62]:
		return watchFired
	case <-ch[63]:
		return watchFired
	case <-timeoutCh:
		return watchTimeout
	}
}

func watchFewDone128(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[127]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-ch[8]:
		return watchFired
	case <-ch[9]:
		return watchFired
	case <-ch[10]:
		return watchFired
	case <-ch[11]:
		return watchFired
	case <-ch[12]:
		return watchFired
	case <-ch[13]:
		return watchFired
	case <-ch[14]:
		return watchFired
	case <-ch[15]:
		return watchFired
	case <-ch[16]:
		return watchFired
	case <-ch[17]:
		return watchFired
	case <-ch[18]:
		return watchFired
	case <-ch[19]:
		return watchFired
	case <-ch[20]:
		return watchFired
	case <-ch[21]:
		return watchFired
	case <-ch[22]:
		return watchFired
	case <-ch[23]:
		return watchFired
	case <-ch[24]:
		return watchFired
	case <-ch[25]:
		return watchFired
	case <-ch[26]:
		return watchFired
	case <-ch[27]:
		return watchFired
	case <-ch[28]:
		return watchFired
	case <-ch[29]:
		return watchFired
	case <-ch[30]:
		return watchFired
	case <-ch[31]:
		return watchFired
	case <-ch[32]:
		return watchFired
	case <-ch[33]:
		return watchFired
	case <-ch[34]:
		return watchFired
	case <-ch[35]:
		return watchFired
	case <-ch[36]:
		return watchFired
	case <-ch[37]:
		return watchFired
	case <-ch[38]:
		return watchFired
	case <-ch[39]:
		return watchFired
	case <-ch[40]:
		return watchFired
	case <-ch[41]:
		return watchFired
	case <-ch[42]:
		return watchFired
	case <-ch[43]:
		return watchFired
	case <-ch[44]:
		return watchFired
	case <-ch[45]:
		return watchFired
	case <-ch[46]:
		return watchFired
	case <-ch[47]:
		return watchFired
	case <-ch[48]:
		return watchFired
	case <-ch[49]:
		return watchFired
	case <-ch[50]:
		return watchFired
	case <-ch[51]:
		return watchFired
	case <-ch[52]:
		return watchFired
	case <-ch[53]:
		return watchFired
	case <-ch[54]:
		return watchFired
	case <-ch[55]:
		return watchFired
	case <-ch[56]:
		return watchFired
	case <-ch[57]:
		return watchFired
	case <-ch[58]:
		return watchFired
	case <-ch[59]:
		return watchFired
	case <-ch[60]:
		return watchFired
	case <-ch[61]:
		return watchFired
	case <-ch[62]:
		return watchFired
	case <-ch[63]:
		return watchFired
	case <-ch[64]:
		return watchFired
	case <-ch[65]:
		return watchFired
	case <-ch[66]:
		return watchFired
	case <-ch[67]:
		return watchFired
	case <-ch[68]:
		return watchFired
	case <-ch[69]:
		return watchFired
	case <-ch[70]:
		return watchFired
	case <-ch[71]:
		return watchFired
	case <-ch[72]:
		return watchFired
	case <-ch[73]:
		return watchFired
	case <-ch[74]:
		return watchFired
	case <-ch[75]:
		return watchFired
	case <-ch[76]:
		return watchFired
	case <-ch[77]:
		return watchFired
	case <-ch[78]:
		return watchFired
	case <-ch[79]:
		return watchFired
	case <-ch[80]:
		return watchFired
	case <-ch[81]:
		return watchFired
	case <-ch[82]:
		return watchFired
	case <-ch[83]:
		return watchFired
	case <-ch[84]:
		return watchFired
	case <-ch[85]:
		return watchFired
	case <-ch[86]:
		return watchFired
	case <-ch[87]:
		return watchFired
	case <-ch[88]:
		return watchFired
	case <-ch[89]:
		return watchFired
	case <-ch[90]:
		return watchFired
	case <-ch[91]:
		return watchFired
	case <-ch[92]:
		return watchFired
	case <-ch[93]:
		return watchFired
	case <-ch[94]:
		return watchFired
	case <-ch[95]:
		return watchFired
	case <-ch[96]:
		return watchFired
	case <-ch[97]:
		return watchFired
	case <-ch[98]:
		return watchFired
	case <-ch[99]:
		return watchFired
	case <-ch[100]:
		return watchFired
	case <-ch[101]:
		return watchFired
	case <-ch[102]:
		return watchFired
	case <-ch[103]:
		return watchFired
	case <-ch[104]:
		return watchFired
	case <-ch[105]:
		return watchFired
	case <-ch[106]:
		return watchFired
	case <-ch[107]:
		return watchFired
	case <-ch[108]:
		return watchFired
	case <-ch[109]:
		return watchFired
	case <-ch[110]:
		return watchFired
	case <-ch[111]:
		return watchFired
	case <-ch[112]:
		return watchFired
	case <-ch[113]:
		return watchFired
	case <-ch[114]:
		return watchFired
	case <-ch[115]:
		return watchFired
	case <-ch[116]:
		return watchFired
	case <-ch[117]:
		return watchFired
	case <-ch[118]:
		return watchFired
	case <-ch[119]:
		return watchFired
	case <-ch[120]:
		return watchFired
	case <-ch[121]:
		return watchFired
	case <-ch[122]:
		return watchFired
	case <-ch[123]:
		return watchFired
	case <-ch[124]:
		return watchFired
	case <-ch[125]:
		return watchFired
	case <-ch[126]:
		return watchFired
	case <-ch[127]:
		return watchFired
	case <-done:
		return watchDone
	}
}

func watchFewTimeout128(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[127]
	select {
	case <-ch[0]:
		return watchFired
	case <-ch[1]:
		return watchFired
	case <-ch[2]:
		return watchFired
	case <-ch[3]:
		return watchFired
	case <-ch[4]:
		return watchFired
	case <-ch[5]:
		return watchFired
	case <-ch[6]:
		return watchFired
	case <-ch[7]:
		return watchFired
	case <-ch[8]:
		return watchFired
	case <-ch[9]:
		return watchFired
	case <-ch[10]:
		return watchFired
	case <-ch[11]:
		return watchFired
	case <-ch[12]:
		return watchFired
	case <-ch[13]:
		return watchFired
	case <-ch[14]:
		return watchFired
	case <-ch[15]:
		return watchFired
	case <-ch[16]:
		return watchFired
	case <-ch[17]:
		return watchFired
	case <-ch[18]:
		return watchFired
	case <-ch[19]:
		return watchFired
	case <-ch[20]:
		return watchFired
	case <-ch[21]:
		return watchFired
	case <-ch[22]:
		return watchFired
	case <-ch[23]:
		return watchFired
	case <-ch[24]:
		return watchFired
	case <-ch[25]:
		return watchFired
	case <-ch[26]:
		return watchFired
	case <-ch[27]:
		return watchFired
	case <-ch[28]:
		return watchFired
	case <-ch[29]:
		return watchFired
	case <-ch[30]:
		return watchFired
	case <-ch[31]:
		return watchFired
	case <-ch[32]:
		return watchFired
	case <-ch[33]:
		return watchFired
	case <-ch[34]:
		return watchFired
	case <-ch[35]:
		return watchFired
	case <-ch[36]:
		return watchFired
	case <-ch[37]:
		return watchFired
	case <-ch[38]:
		return watchFired
	case <-ch[39]:
		return watchFired
	case <-ch[40]:
		return watchFired
	case <-ch[41]:
		return watchFired
	case <-ch[42]:
		return watchFired
	case <-ch[43]:
		return watchFired
	case <-ch[44]:
		return watchFired
	case <-ch[45]:
		return watchFired
	case <-ch[46]:
		return watchFired
	case <-ch[47]:
		return watchFired
	case <-ch[48]:
		return watchFired
	case <-ch[49]:
		return watchFired
	case <-ch[50]:
		return watchFired
	case <-ch[51]:
		return watchFired
	case <-ch[52]:
		return watchFired
	case <-ch[53]:
		return watchFired
	case <-ch[54]:
		return watchFired
	case <-ch[55]:
		return watchFired
	case <-ch[56]:
		return watchFired
	case <-ch[57]:
		return watchFired
	case <-ch[58]:
		return watchFired
	case <-ch[59]:
		return watchFired
	case <-ch[60]:
		return watchFired
	case <-ch[61]:
		return watchFired
	case <-ch[62]:
		return watchFired
	case <-ch[63]:
		return watchFired
	case <-ch[64]:
		return watchFired
	case <-ch[65]:
		return watchFired
	case <-ch[66]:
		return watchFired
	case <-ch[67]:
		return watchFired
	case <-ch[68]:
		return watchFired
	case <-ch[69]:
		return watchFired
	case <-ch[70]:
		return watchFired
	case <-ch[71]:
		return watchFired
	case <-ch[72]:
		return watchFired
	case <-ch[73]:
		return watchFired
	case <-ch[74]:
		return watchFired
	case <-ch[75]:
		return watchFired
	case <-ch[76]:
		return watchFired
	case <-ch[77]:
		return watchFired
	case <-ch[78]:
		return watchFired
	case <-ch[79]:
		return watchFired
	case <-ch[80]:
		return watchFired
	case <-ch[81]:
		return watchFired
	case <-ch[82]:
		return watchFired
	case <-ch[83]:
		return watchFired
	case <-ch[84]:
		return watchFired
	case <-ch[85]:
		return watchFired
	case <-ch[86]:
		return watchFired
	case <-ch[87]:
		return watchFired
	case <-ch[88]:
		return watchFired
	case <-ch[89]:
		return watchFired
	case <-ch[90]:
		return watchFired
	case <-ch[91]:
		return watchFired
	case <-ch[92]:
		return watchFired
	case <-ch[93]:
		return watchFired
	case <-ch[94]:
		return watchFired
	case <-ch[95]:
		return watchFired
	case <-ch[96]:
		return watchFired
	case <-ch[97]:
		return watchFired
	case <-ch[98]:
		return watchFired
	case <-ch[99]:
		return watchFired
	case <-ch[100]:
		return watchFired
	case <-ch[101]:
		return watchFired
	case <-ch[102]:
		return watchFired
	case <-ch[103]:
		return watchFired
	case <-ch[104]:
		return watchFired
	case <-ch[105]:
		return watchFired
	case <-ch[106]:
		return watchFired
	case <-ch[107]:
		return watchFired
	case <-ch[108]:
		return watchFired
	case <-ch[109]:
		return watchFired
	case <-ch[110]:
		return watchFired
	case <-ch[111]:
		return watchFired
	case <-ch[112]:
		return watchFired
	case <-ch[113]:
		return watchFired
	case <-ch[114]:
		return watchFired
	case <-ch[115]:
		return watchFired
	case <-ch[116]:
		return watchFired
	case <-ch[117]:
		return watchFired
	case <-ch[118]:
		return watchFired
	case <-ch[119]:
		return watchFired
	case <-ch[120]:
		return watchFired
	case <-ch[121]:
		return watchFired
	case <-ch[122]:
		return watchFired
	case <-ch[123]:
		return watchFired
	case <-ch[124]:
		return watchFired
	case <-ch[125]:
		return watchFired
	case <-ch[126]:
		return watchFired
	case <-ch[127]:
		return watchFired
	case <-timeoutCh:
		return watchTimeout
	}
}
