// Copyright IBM Corp. 2015, 2026
// SPDX-License-Identifier: MPL-2.0
//
// Modifications Copyright (c) 2026 Ville Vesilehto
// Derived from github.com/hashicorp/go-memdb watch-gen/main.go @ 7d3fdd5.
// Upstream generates one 32-way select. This version generates a ladder of
// selects (1, 2, 4 ... 128 channels) that also wait on a done channel and a
// timeout channel directly, emits the license header that upstream's template
// forgot (running go generate there strips it), and formats its output.

// This tool generates the special-case code for a small number of watchers
// which runs all the watches in a single select vs. needing to spawn a
// goroutine for each one.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"text/template"
)

// aFew is kept at upstream's value: it is part of what the (unmodified)
// upstream tests sweep over. It no longer limits anything by itself.
const aFew = 32

// tiers are the select sizes to generate. A watch set of n channels runs in
// the smallest tier that holds it, so waiting on one channel does not pay for
// a 32-way select. The largest tier is also the chunk size used when a set is
// too big for a single select and is spread over goroutines.
var tiers = []int{1, 2, 4, 8, 16, 32, 64, 128}

// fanoutChunk is the number of channels per helper goroutine when a watch set
// is too big for one select. Measured on the blocking path with 256 and 1024
// channels: 32 beats 64 and 128 (setting up a select costs n log n), and a
// 32-channel chunk is a 256-byte allocation, which -- unlike one big slice for
// the whole set -- needs no malloc header and wastes no size-class slack.
const fanoutChunk = 32

// source is the template we use to generate the source file.
const source = `// Copyright IBM Corp. 2015, 2026
// SPDX-License-Identifier: MPL-2.0
//
// Modifications Copyright (c) 2026 Ville Vesilehto
// Derived from github.com/hashicorp/go-memdb watch_few.go @ 7d3fdd5.

// Code generated by watch-gen/main.go; DO NOT EDIT.

package memdb

{{.Directive}} sh -c "go run watch-gen/main.go >watch_few.go"

import (
	"time"
)

// aFew is upstream's name for the number of channels one select handles. It
// is kept because upstream's tests refer to it; see maxFew for the real limit.
const aFew = {{.AFew}}

// maxFew is the largest number of channels a single select waits on.
const maxFew = {{.Max}}

// fanoutChunk is how many channels each helper goroutine of a bigger watch set
// waits on.
const fanoutChunk = {{.Chunk}}

// watchChunk is what a helper goroutine runs: the select over exactly
// fanoutChunk channels, called directly. Going through watchFewDone would put
// its frame between the goroutine and the select, and on a new goroutine's
// small stack that is enough to move the first stack growth from somewhere
// inside the runtime to the entry of the big select function -- where growing
// is expensive, because the runtime walks that function's long stack table to
// size the new stack. Measured on x86-64, it made a watch on 1024 channels 6%
// slower than upstream's.
func watchChunk(done <-chan struct{}, ch []<-chan struct{}) int {
	return watchFewDone{{.Chunk}}(done, ch)
}

// What ended a wait.
const (
	watchFired   = iota // one of the watch channels
	watchDone           // the done channel (a cancelled context)
	watchTimeout        // the timeout channel
)

// A wait ends on a watch channel or on the one "other" channel of the call:
// the done channel of a context (WatchCtx, and the helper goroutines of a big
// set) or a timeout channel (Watch). Each gets its own ladder of selects, so
// that no select carries an arm its caller never uses.

// watchFewDone waits on the first n channels of ch and on done, in a single
// select of the smallest sufficient size. Unused channels and done may be nil:
// a nil channel is never ready.
func watchFewDone(n int, done <-chan struct{}, ch []<-chan struct{}) int {
	switch {
{{- range .Tiers}}
	case n <= {{.}}:
		return watchFewDone{{.}}(done, ch)
{{- end}}
	}
	panic("memdb: watchFewDone called with too many channels")
}

// watchFewTimeout is watchFewDone for a timeout channel.
func watchFewTimeout(n int, timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	switch {
{{- range .Tiers}}
	case n <= {{.}}:
		return watchFewTimeout{{.}}(timeoutCh, ch)
{{- end}}
	}
	panic("memdb: watchFewTimeout called with too many channels")
}
{{range $tier := .Tiers}}
func watchFewDone{{$tier}}(done <-chan struct{}, ch []<-chan struct{}) int {
	_ = ch[{{last $tier}}]
	select {
{{- range $i := upto $tier}}
	case <-ch[{{$i}}]:
		return watchFired
{{- end}}
	case <-done:
		return watchDone
	}
}

func watchFewTimeout{{$tier}}(timeoutCh <-chan time.Time, ch []<-chan struct{}) int {
	_ = ch[{{last $tier}}]
	select {
{{- range $i := upto $tier}}
	case <-ch[{{$i}}]:
		return watchFired
{{- end}}
	case <-timeoutCh:
		return watchTimeout
	}
}
{{end}}`

// render prints the formatted template to stdout.
func render() error {
	funcs := template.FuncMap{
		"upto": func(n int) []int {
			out := make([]int, n)
			for i := range out {
				out[i] = i
			}
			return out
		},
		"last": func(n int) int { return n - 1 },
	}
	tmpl, err := template.New("watch").Funcs(funcs).Parse(source)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	data := struct {
		AFew, Max, Chunk int
		Tiers            []int
		Directive        string
	}{
		AFew:  aFew,
		Max:   tiers[len(tiers)-1],
		Chunk: fanoutChunk,
		Tiers: tiers,
		// Spelled out here rather than in the template: go generate looks
		// for its directive at the start of any line of any Go file, this
		// one included, and would run it from the wrong directory.
		Directive: "//go:" + "generate",
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}
	_, err = os.Stdout.Write(out)
	return err
}

func main() {
	if err := render(); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	} else {
		os.Exit(0)
	}
}
